services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_NAME: ${BOT_NAME}
      PORT: ${PORT}
    container_name: my-app
