name: Build and Deploy Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Save Docker image to file
        run: docker save my-app -o my-app.tar

      - name: Copy Docker image and compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 45.12.236.8
          username: root
          key: ${{ secrets.MY_SECRET }}
          source: |
            my-app.tar
            docker-compose.yml
          target: /root/app

      - name: Deploy Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 45.12.236.8
          username: root
          key: ${{ secrets.MY_SECRET }}
          script: |
            cd /root/app
            docker load -i my-app.tar
            docker compose down || true
            docker compose up -d
